spring:
  application:
    name: library-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/library_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "@Nitish123"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 25
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

  cache:
    type: simple

jwt:
  secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

library:
  loan:
    reminder-days-before-due: 2
    max-renewals-default: 2
  fine:
    daily-rate-default: 5.00
    max-fine-default: 500.00

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8085

logging:
  level:
    com.library.lms: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
